# Generated by Django 3.2.25 on 2024-11-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0005_calendar_order_snack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day',
            field=models.DateField(),
        ),
    ]
