# Generated by Django 3.2.25 on 2024-11-22 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0008_auto_20241122_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='snacks2school.calendar'),
        ),
    ]
