# Generated by Django 3.2.25 on 2024-11-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0009_alter_day_calendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='user',
            new_name='seller',
        ),
    ]
