# Generated by Django 3.2.25 on 2024-11-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0012_auto_20241122_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store_name',
        ),
    ]
