# Generated by Django 3.2.25 on 2024-11-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0014_snack_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='snack_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
