# Generated by Django 3.2.25 on 2024-12-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0016_auto_20241126_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='snack_images/'),
        ),
    ]
