# Generated by Django 3.2.25 on 2024-12-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0018_auto_20241209_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredient_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='snack',
            name='ingredienti',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.AddField(
            model_name='snack',
            name='ingredient',
            field=models.ManyToManyField(related_name='snacks', to='snacks2school.Ingredient'),
        ),
    ]
