# Generated by Django 3.2.25 on 2024-12-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0020_alter_snack_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='ingredient',
            field=models.ManyToManyField(related_name='snacks', to='snacks2school.Ingredient'),
        ),
    ]
