# Generated by Django 3.2.25 on 2024-12-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0022_alter_snack_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
