# Generated by Django 3.2.25 on 2024-12-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0023_rename_ingredient_snack_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='price',
            new_name='net_price',
        ),
        migrations.AddField(
            model_name='snack',
            name='gross_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
