# Generated by Django 3.2.25 on 2024-12-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0024_auto_20241210_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='gross_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
