# Generated by Django 3.2.25 on 2024-12-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0025_alter_snack_gross_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='is_drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snack',
            name='is_food',
            field=models.BooleanField(default=True),
        ),
    ]
