# Generated by Django 3.2.25 on 2024-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0026_auto_20241210_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='is_drink',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='is_food',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
