# Generated by Django 3.2.25 on 2024-12-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0027_auto_20241210_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='is_drink',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='is_food',
        ),
    ]
