# Generated by Django 3.2.25 on 2024-12-10 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0028_auto_20241210_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='snack_ingredients', to='snacks2school.Ingredient'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snack_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gross_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='snack_images/')),
                ('ingredients', models.ManyToManyField(blank=True, null=True, related_name='drink_ingredients', to='snacks2school.Ingredient')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drink_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
