# Generated by Django 3.2.25 on 2024-12-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0030_auto_20241211_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
