# Generated by Django 3.2.25 on 2024-12-11 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0034_auto_20241211_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='snacks2school.calendar')),
                ('drinks', models.ManyToManyField(blank=True, to='snacks2school.Drink')),
                ('snacks', models.ManyToManyField(blank=True, to='snacks2school.Snack')),
            ],
        ),
    ]
