# Generated by Django 3.2.25 on 2024-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0035_calendarday'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='calendarday',
            index=models.Index(fields=['date'], name='snacks2scho_date_8995b8_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarday',
            index=models.Index(fields=['calendar', 'date'], name='snacks2scho_calenda_b98475_idx'),
        ),
    ]
