# Generated by Django 3.2.25 on 2024-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0036_auto_20241212_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_wallet_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
