# Generated by Django 3.2.25 on 2024-12-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0038_auto_20241219_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='classes',
        ),
    ]
