# Generated by Django 3.2.25 on 2024-12-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0039_remove_school_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='schools', to='snacks2school.Class'),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
