# Generated by Django 3.2.25 on 2024-12-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0042_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='code',
        ),
    ]
