# Generated by Django 3.2.25 on 2024-12-20 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0043_remove_province_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snacks2school.province'),
        ),
    ]
