# Generated by Django 3.2.25 on 2024-12-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0044_alter_school_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='school',
        ),
    ]
