# Generated by Django 3.2.25 on 2024-12-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0045_remove_class_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='classes',
        ),
    ]
