# Generated by Django 3.2.25 on 2024-12-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0046_remove_school_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='address',
        ),
    ]
