# Generated by Django 3.2.25 on 2024-12-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0052_auto_20241230_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='schools',
        ),
        migrations.AddField(
            model_name='class',
            name='campus',
            field=models.ManyToManyField(related_name='classes', to='snacks2school.Campus'),
        ),
    ]
