# Generated by Django 3.2.25 on 2024-12-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0053_auto_20241230_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='campus',
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ManyToManyField(related_name='classes', to='snacks2school.School'),
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
