# Generated by Django 3.2.25 on 2024-12-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0054_auto_20241230_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
