# Generated by Django 3.2.25 on 2024-12-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0055_school_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='school_classes',
            field=models.ManyToManyField(related_name='classes', to='snacks2school.Class'),
        ),
    ]
