# Generated by Django 3.2.25 on 2024-12-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0056_auto_20241230_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes', to='snacks2school.Class'),
        ),
    ]
