# Generated by Django 3.2.25 on 2024-12-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0057_alter_school_school_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_classes',
            field=models.ManyToManyField(related_name='classes', to='snacks2school.Class'),
        ),
    ]
