# Generated by Django 3.2.25 on 2025-01-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks2school', '0060_auto_20241231_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
