version: "3.8"

services:
  django:
    image: lucamatta/snacks2school-backend:latest
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  nuxt:
    image: lucamatta/snacks2school-frontend:latest
    container_name: nuxt
    ports:
      - "3001:3001"
    depends_on:
      - django

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
      - nuxt
